version: 1.2.{build}
image: Visual Studio 2017
configuration: Release
platform: Win32
before_build:
- cmd: >-
    git clone https://github.com/SFML/SFML.git

    cd SFML

    mkdir ..\extlibs

    mkdir build

    cd build

    cmake -DCMAKE_INSTALL_PREFIX=../../extlibs -DBUILD_SHARED_LIBS=FALSE -DSFML_USE_STATIC_STD_LIBS=TRUE ..

    msbuild /m INSTALL.vcxproj

    cd ..\..\

    rmdir SFML /Q /S
build:
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    mkdir Schiffbruch

    xcopy bin\* Schiffbruch\ /E

    copy build\Release\Schiffbruch.exe Schiffbruch

    copy extlibs\bin\openal32.dll Schiffbruch
artifacts:
- path: Schiffbruch
  name: Schiffbruch
deploy:
- provider: GitHub
  release: Schiffbruch
  auth_token:
    secure: krNF+BFj+w2O15FO6BiPJ1J1NQ7QffQYWKF2qexIigODVTNv4t8sZTG3+YGsR8rt
  artifact: Schiffbruch
  draft: true
  on:
    branch: master